/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.1.1/userguide/multi_project_builds.html
 */

dependencyResolutionManagement {

    versionCatalogs {
        create("libs") {
            version("arrow", "2.0.1")
            version("suspendapp", "0.5.0")
            version("ktor", "3.3.1")
            version("ktor-swagger-ui", "5.4.0")
            version("ktor-openapi", "5.4.0")
            version("schema-kenerator-serialization", "2.5.0")
            version("kotlin-logging", "7.0.3")
            version("hoplite", "2.8.2")
            version("prometheus", "1.12.4")
            version("logback", "1.5.19")
            version("logstash", "7.4")
            version("kotlinx-serialization", "1.9.0")
            version("kotlinx-schema", "0.5.0")
            version("json-schema-validator", "0.5.4")

            library("arrow-core", "io.arrow-kt", "arrow-core").versionRef("arrow")
            library("arrow-functions", "io.arrow-kt", "arrow-functions").versionRef("arrow")
            library("arrow-suspendapp", "io.arrow-kt", "suspendapp").versionRef("suspendapp")
            library("arrow-suspendapp-ktor", "io.arrow-kt", "suspendapp-ktor").versionRef("suspendapp")

            library("hoplite-core", "com.sksamuel.hoplite", "hoplite-core").versionRef("hoplite")
            library("hoplite-hocon", "com.sksamuel.hoplite", "hoplite-hocon").versionRef("hoplite")

            library("ktor-server-core", "io.ktor", "ktor-server-core").versionRef("ktor")
            library("ktor-server-netty", "io.ktor", "ktor-server-netty").versionRef("ktor")
            library("ktor-server-content-negotiation", "io.ktor", "ktor-server-content-negotiation").versionRef("ktor")
            library("ktor-client-content-negotiation", "io.ktor", "ktor-client-content-negotiation").versionRef("ktor")
            library("ktor-serialization-kotlinx-json", "io.ktor", "ktor-serialization-kotlinx-json").versionRef("ktor")

            library("ktor-server-metrics-micrometer", "io.ktor", "ktor-server-metrics-micrometer").versionRef("ktor")
            library(
                "micrometer-registry-prometheus",
                "io.micrometer",
                "micrometer-registry-prometheus"
            ).versionRef("prometheus")

            library("ktor-swagger-ui", "io.github.smiley4", "ktor-swagger-ui").versionRef("ktor-swagger-ui")
            library("ktor-openapi", "io.github.smiley4", "ktor-openapi").versionRef("ktor-openapi")
            library("schema-kenerator-serialization", "io.github.smiley4", "schema-kenerator-serialization").versionRef("schema-kenerator-serialization")

            library("kotlin-logging", "io.github.oshai", "kotlin-logging-jvm").versionRef("kotlin-logging")
            library("logback-classic", "ch.qos.logback", "logback-classic").versionRef("logback")
            library("logback-logstash", "net.logstash.logback", "logstash-logback-encoder").versionRef("logstash")

            library("kotlinx-serialization-json", "org.jetbrains.kotlinx", "kotlinx-serialization-json").versionRef("kotlinx-serialization")
            library("kotlinx-schema-ksp", "org.jetbrains.kotlinx", "kotlinx-schema-ksp").versionRef("kotlinx-schema")
            library("kotlinx-schema-annotations", "org.jetbrains.kotlinx", "kotlinx-schema-annotations").versionRef("kotlinx-schema")
            library("kotlinx-schema-json", "org.jetbrains.kotlinx", "kotlinx-schema-json").versionRef("kotlinx-schema")

            library("json-schema-validator", "io.github.optimumcode", "json-schema-validator").versionRef("json-schema-validator")

            bundle("prometheus", listOf("ktor-server-metrics-micrometer", "micrometer-registry-prometheus"))
            bundle("logging", listOf("logback-classic", "logback-logstash"))
        }

        create("testLibs") {
            version("arrow", "2.0.0")
            version("ktor", "3.3.1")
            version("ktor-server-test", "3.3.1")
            version("kotest", "5.9.1")
            version("testcontainers", "1.18.1")
            version("kotest-extensions", "2.0.2")

            library("ktor-server-test-host", "io.ktor", "ktor-server-test-host").versionRef("ktor-server-test")
            library("ktor-client-mock", "io.ktor", "ktor-client-mock").versionRef("ktor")

            library("kotest-runner-junit5", "io.kotest", "kotest-runner-junit5").versionRef("kotest")
            library("kotest-framework-datatest", "io.kotest", "kotest-framework-datatest").versionRef("kotest")
            library("kotest-extensions-jvm", "io.kotest", "kotest-extensions-jvm").versionRef("kotest")

            library(
                "kotest-extensions-testcontainers",
                "io.kotest.extensions",
                "kotest-extensions-testcontainers"
            ).versionRef("kotest-extensions")

            library("kotest-assertions-arrow", "io.kotest.extensions", "kotest-assertions-arrow").versionRef("arrow")

            library("testcontainers", "org.testcontainers", "testcontainers").versionRef("testcontainers")
            library("testcontainers-postgresql", "org.testcontainers", "postgresql").versionRef("testcontainers")

            bundle("kotest", listOf("kotest-runner-junit5", "kotest-framework-datatest"))
        }
    }

    repositories {
        mavenCentral()
        maven {
            name = "Nav token-support"
            url = uri("https://maven.pkg.github.com/navikt/token-support")
            credentials {
                username = "token"
                password = System.getenv("GITHUB_TOKEN")
            }
        }
        maven {
            name = "Mock OAUTH2 server"
            url = uri("https://maven.pkg.github.com/navikt/mock-oauth2-server")
            credentials {
                username = "token"
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

rootProject.name = "helsemelding-json-schema"

include("json-schema-server")
include("json-schema-core")
